name: mobile
description: "Cliente móvil del modelador UML."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.1
  http: ^1.2.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app/icon.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: assets/app/icon.png
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: assets/app/icon.png
    icon_size: 256
  macos:
    generate: true
    image_path: assets/app/icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/app/
