name: mobile
description: "Cliente móvil del modelador UML."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.1
  http: ^1.2.2
  http_parser: ^4.1.2
  llama_cpp_dart: 0.9.0-dev.10
  shared_preferences: ^2.3.2
  archive: ^4.0.9
  connectivity_plus: ^6.1.4
  crypto: ^3.0.6
  drift: ^2.28.0
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  record: ^6.2.1
  share_plus: ^11.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  drift_dev: ^2.28.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app/icon.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: assets/app/icon.png
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: assets/app/icon.png
    icon_size: 256
  macos:
    generate: true
    image_path: assets/app/icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/app/
