# Generated by Django 5.1.6 on 2026-09-08 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaclassRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('diagram_type', models.CharField(max_length=64)),
                ('definitions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('version', 'diagram_type'), name='unique_metaclass_registry')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('mda_level', models.CharField(choices=[('CIM', 'CIM'), ('PIM', 'PIM'), ('PSM', 'PSM'), ('UNSPECIFIED', 'No especificado')], default='UNSPECIFIED', max_length=16)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelOperation',
            fields=[
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(choices=[('user', 'Usuario'), ('import', 'Importación'), ('ai', 'IA'), ('restore', 'Restauración')], default='user', max_length=16)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=32)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('base_revision', models.PositiveBigIntegerField(default=0)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('server_revision', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_operations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='modeling.project')),
            ],
            options={
                'ordering': ('server_revision',),
            },
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=128)),
                ('code_hint', models.CharField(max_length=12)),
                ('role', models.CharField(choices=[('owner', 'Propietario'), ('editor', 'Editor'), ('viewer', 'Lector')], default='editor', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_invites', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to='modeling.project')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=64)),
                ('external_id', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.UUIDField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identifiers', to='modeling.project')),
            ],
        ),
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('diagram_type', models.CharField(max_length=64)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_diagrams', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to='modeling.project')),
            ],
        ),
        migrations.CreateModel(
            name='AiProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('context', models.JSONField(default=dict)),
                ('proposal', models.JSONField(default=dict)),
                ('warnings', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('ready', 'Lista'), ('applied', 'Aplicada'), ('cancelled', 'Cancelada'), ('invalid', 'Inválida')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_proposals', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_proposals', to='modeling.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Propietario'), ('editor', 'Editor'), ('viewer', 'Lector')], max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='modeling.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveBigIntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('reason', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_snapshots', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='modeling.project')),
            ],
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('path', models.CharField(max_length=255)),
                ('rejected_value', models.JSONField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accepted_conflicts', to='modeling.modeloperation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='modeling.project')),
                ('rejected_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_conflicts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UmlElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metaclass', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('external_ids', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_uml_elements', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='modeling.project')),
            ],
        ),
        migrations.CreateModel(
            name='DiagramNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('width', models.FloatField(default=180)),
                ('height', models.FloatField(default=80)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='modeling.diagram')),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagram_nodes', to='modeling.umlelement')),
            ],
        ),
        migrations.CreateModel(
            name='UmlPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('mda_level', models.CharField(choices=[('CIM', 'CIM'), ('PIM', 'PIM'), ('PSM', 'PSM'), ('UNSPECIFIED', 'No especificado')], default='UNSPECIFIED', max_length=16)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='modeling.umlpackage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='modeling.project')),
            ],
        ),
        migrations.AddField(
            model_name='umlelement',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='modeling.umlpackage'),
        ),
        migrations.CreateModel(
            name='UmlRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(max_length=80)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('external_ids', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='modeling.project')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='modeling.umlelement')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='modeling.umlelement')),
            ],
        ),
        migrations.CreateModel(
            name='DiagramEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='modeling.diagram')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='modeling.diagramnode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='modeling.diagramnode')),
                ('relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagram_edges', to='modeling.umlrelationship')),
            ],
        ),
        migrations.AddConstraint(
            model_name='modeloperation',
            constraint=models.UniqueConstraint(fields=('project', 'server_revision'), name='unique_project_revision'),
        ),
        migrations.AddConstraint(
            model_name='externalidentifier',
            constraint=models.UniqueConstraint(fields=('project', 'provider', 'external_id'), name='unique_external_identifier'),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_member'),
        ),
    ]
