"""Versioned subset of UML 2.5.1 shared by API, editor and validators."""

UML_REGISTRY_VERSION = "uml-2.5.1-subset-2"

DIAGRAM_TYPES = (
    "class",
    "object",
    "component",
    "composite_structure",
    "package",
    "deployment",
    "profile",
    "use_case",
    "activity",
    "state_machine",
    "sequence",
    "communication",
    "interaction_overview",
    "timing",
)

ELEMENT_TYPES = (
    "Class",
    "Interface",
    "Enumeration",
    "DataType",
    "PrimitiveType",
    "Signal",
    "Comment",
    "Constraint",
    "Object",
    "InstanceSpecification",
    "Model",
    "Component",
    "Port",
    "Part",
    "Connector",
    "Collaboration",
    "CollaborationUse",
    "Node",
    "Device",
    "ExecutionEnvironment",
    "DeploymentSpecification",
    "Artifact",
    "Package",
    "Profile",
    "Stereotype",
    "Extension",
    "Actor",
    "UseCase",
    "Activity",
    "Action",
    "CallBehaviorAction",
    "CallOperationAction",
    "SendSignalAction",
    "AcceptEventAction",
    "ObjectNode",
    "ActivityParameterNode",
    "CentralBufferNode",
    "DataStoreNode",
    "ActivityPartition",
    "InterruptibleActivityRegion",
    "DecisionNode",
    "MergeNode",
    "InitialNode",
    "ActivityFinalNode",
    "FlowFinalNode",
    "ForkNode",
    "JoinNode",
    "StateMachine",
    "State",
    "FinalState",
    "Pseudostate",
    "Region",
    "Lifeline",
    "Interaction",
    "ExecutionSpecification",
    "CombinedFragment",
    "InteractionUse",
    "StateInvariant",
    "Continuation",
    "DestructionOccurrenceSpecification",
    "Gate",
    "TimeObservation",
    "DurationObservation",
    "TimeConstraint",
    "DurationConstraint",
)

RELATIONSHIP_TYPES = (
    "Association",
    "Aggregation",
    "Composition",
    "Generalization",
    "Dependency",
    "Realization",
    "Include",
    "Extend",
    "ControlFlow",
    "ObjectFlow",
    "Transition",
    "Message",
    "Trace",
    "Extension",
)

DIAGRAM_DEFINITIONS = {
    "class": {"elements": ["Class", "Actor", "Interface", "Enumeration", "DataType", "PrimitiveType", "Signal", "Package", "Comment", "Constraint"], "relationships": ["Association", "Aggregation", "Composition", "Generalization", "Dependency", "Realization"]},
    "object": {"elements": ["Object", "InstanceSpecification", "Class", "Package", "Comment", "Constraint"], "relationships": ["Association", "Dependency"]},
    "component": {"elements": ["Component", "Interface", "Port", "Artifact", "Package", "Comment"], "relationships": ["Dependency", "Realization", "Association"]},
    "composite_structure": {"elements": ["Class", "Part", "Port", "Connector", "Collaboration", "CollaborationUse", "Comment"], "relationships": ["Association", "Dependency"]},
    "package": {"elements": ["Package", "Model", "Profile", "Comment"], "relationships": ["Dependency", "Trace"]},
    "deployment": {"elements": ["Node", "Device", "ExecutionEnvironment", "Artifact", "DeploymentSpecification", "Component", "Comment"], "relationships": ["Dependency", "Association"]},
    "profile": {"elements": ["Profile", "Stereotype", "Class", "Enumeration", "DataType", "Extension", "Comment"], "relationships": ["Extension", "Generalization"]},
    "use_case": {"elements": ["Actor", "UseCase", "Package", "Comment", "Constraint"], "relationships": ["Association", "Include", "Extend", "Generalization"]},
    "activity": {"elements": ["Activity", "Action", "CallBehaviorAction", "CallOperationAction", "SendSignalAction", "AcceptEventAction", "ObjectNode", "ActivityParameterNode", "CentralBufferNode", "DataStoreNode", "ActivityPartition", "InterruptibleActivityRegion", "DecisionNode", "MergeNode", "InitialNode", "ActivityFinalNode", "FlowFinalNode", "ForkNode", "JoinNode", "Comment"], "relationships": ["ControlFlow", "ObjectFlow"]},
    "state_machine": {"elements": ["StateMachine", "State", "FinalState", "Pseudostate", "Region", "Comment"], "relationships": ["Transition"]},
    "sequence": {"elements": ["Lifeline", "Interaction", "ExecutionSpecification", "CombinedFragment", "InteractionUse", "StateInvariant", "Continuation", "DestructionOccurrenceSpecification", "Gate", "Comment"], "relationships": ["Message"]},
    "communication": {"elements": ["Lifeline", "Object", "Interaction", "Comment"], "relationships": ["Message", "Association"]},
    "interaction_overview": {"elements": ["Interaction", "InteractionUse", "Activity", "DecisionNode", "MergeNode", "InitialNode", "ActivityFinalNode", "FlowFinalNode", "ForkNode", "JoinNode", "Comment"], "relationships": ["ControlFlow"]},
    "timing": {"elements": ["Lifeline", "State", "StateInvariant", "TimeObservation", "DurationObservation", "TimeConstraint", "DurationConstraint", "Interaction", "Comment"], "relationships": ["Message", "Transition"]},
}


def registry_payload():
    return {
        "version": UML_REGISTRY_VERSION,
        "diagram_types": list(DIAGRAM_TYPES),
        "element_types": list(ELEMENT_TYPES),
        "relationship_types": list(RELATIONSHIP_TYPES),
        "diagrams": DIAGRAM_DEFINITIONS,
    }


def diagram_definition(diagram_type):
    return DIAGRAM_DEFINITIONS.get(diagram_type, {"elements": [], "relationships": []})
