from django.urls import path

from .views import (
    ai_apply,
    ai_explain,
    ai_proposals,
    ai_transcription,
    create_invite,
    diagram_edges,
    diagram_edge_detail,
    diagram_nodes,
    diagram_node_detail,
    export_interchange,
    expert_rules,
    import_interchange,
    import_project,
    join_project,
    list_invites,
    local_model_manifest,
    project_detail,
    project_history,
    project_members,
    project_member_detail,
    project_operations,
    project_resource,
    project_resource_detail,
    project_snapshots,
    projects,
    registry,
    resolve_conflict,
    restore_snapshot,
    revoke_invite,
    validate_project,
    websocket_ticket,
)


urlpatterns = [
    path("registry/", registry, name="uml-registry"),
    path("expert-rules/", expert_rules, name="expert-rules"),
    path("ai/local-model/manifest/", local_model_manifest, name="local-model-manifest"),
    path("projects/", projects, name="projects"),
    path("projects/join/", join_project, name="project-join"),
    path("projects/import/", import_project, name="project-import"),
    path("projects/<uuid:project_id>/", project_detail, name="project-detail"),
    path("projects/<uuid:project_id>/members/", project_members, name="project-members"),
    path("projects/<uuid:project_id>/members/<uuid:member_id>/", project_member_detail, name="project-member-detail"),
    path("projects/<uuid:project_id>/sync/ticket/", websocket_ticket, name="project-ws-ticket"),
    path("projects/<uuid:project_id>/invites/", list_invites, name="project-invites"),
    path("projects/<uuid:project_id>/invites/create/", create_invite, name="project-invite-create"),
    path("projects/<uuid:project_id>/invites/<uuid:invite_id>/revoke/", revoke_invite, name="project-invite-revoke"),
    path("projects/<uuid:project_id>/history/", project_history, name="project-history"),
    path("projects/<uuid:project_id>/conflicts/<uuid:conflict_id>/resolve/", resolve_conflict, name="project-conflict-resolve"),
    path("projects/<uuid:project_id>/snapshots/", project_snapshots, name="project-snapshots"),
    path("projects/<uuid:project_id>/snapshots/<uuid:snapshot_id>/restore/", restore_snapshot, name="project-snapshot-restore"),
    path("projects/<uuid:project_id>/validate/", validate_project, name="project-validate"),
    path("projects/<uuid:project_id>/operations/", project_operations, name="project-operations"),
    path("projects/<uuid:project_id>/<str:resource>/", project_resource, name="project-resource"),
    path("projects/<uuid:project_id>/<str:resource>/<uuid:resource_id>/", project_resource_detail, name="project-resource-detail"),
    path("projects/<uuid:project_id>/diagrams/<uuid:diagram_id>/nodes/", diagram_nodes, name="diagram-nodes"),
    path("projects/<uuid:project_id>/diagrams/<uuid:diagram_id>/nodes/<uuid:node_id>/", diagram_node_detail, name="diagram-node-detail"),
    path("projects/<uuid:project_id>/diagrams/<uuid:diagram_id>/edges/", diagram_edges, name="diagram-edges"),
    path("projects/<uuid:project_id>/diagrams/<uuid:diagram_id>/edges/<uuid:edge_id>/", diagram_edge_detail, name="diagram-edge-detail"),
    path("projects/<uuid:project_id>/interchange/export/", export_interchange, name="interchange-export"),
    path("projects/<uuid:project_id>/interchange/import/", import_interchange, name="interchange-import"),
    path("projects/<uuid:project_id>/ai/proposals/", ai_proposals, name="ai-proposals"),
    path("projects/<uuid:project_id>/ai/transcriptions/", ai_transcription, name="ai-transcription"),
    path("projects/<uuid:project_id>/ai/explain/", ai_explain, name="ai-explain"),
    path("projects/<uuid:project_id>/ai/proposals/<uuid:proposal_id>/apply/", ai_apply, name="ai-apply"),
]
